### ISSUE TITLE
Fireside with NewNode 2.0.5 crashes on devices with Android API < 31

### ISSUE THREAD

**Issue by IvanSeleznevSpb** [clostra/newnode#125]
Fireside v0.7.7-dev1 with NewNode 2.0.5 crashes on devices with Android API < 31 (Android 11 and lower) with error:
```
2022-05-13 14:46:55.518 11108-11108/? E/NewNode: version 2.0.5 started
2022-05-13 14:46:55.534 11108-11108/? E/NewNode: NearbyHelper
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/nearby/connection/Strategy;
        at com.clostra.newnode.internal.NearbyHelper.<init>(NearbyHelper.java:39)
        at com.clostra.newnode.internal.NewNode.init(NewNode.java:233)
        at com.clostra.newnode.NewNode.init(NewNode.java:88)
        at com.clostra.nnm.ApplicationContext.onCreate(ApplicationContext.java:124)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6017)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1727)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```
Most likely the crash is caused by the lack of bluetooth permissions.
```
2022-05-13 14:46:55.918 11108-11108/? E/PermissionActivity: Permission android.permission.BLUETOOTH_ADVERTISE is not granted
2022-05-13 14:46:55.918 11108-11108/? E/PermissionActivity: Permission android.permission.BLUETOOTH_CONNECT is not granted
2022-05-13 14:46:55.918 11108-11108/? E/PermissionActivity: Permission android.permission.BLUETOOTH_SCAN is not granted
```
These permissions appeared only in API 31 (Android 12). For API < 31 these permissions should be changed to BLUETOOTH and BLUETOOTH_ADMIN
https://developers.google.com/nearby/connections/strategies

**Comment by ghazel** [comment]
Can you try with the latest version?
