### ISSUE TITLE
[Android] Android 14 Support feature request

### ISSUE THREAD

**Issue by gurupriyan-ks** [clostra/newnode#144]
The below error is thrown when NewNode SDK is initialised in Android 14 devices, can you please support on this? 

```
Fatal Exception: java.lang.SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
       at android.os.Parcel.createException(Parcel.java:3053)
       at android.os.Parcel.readException(Parcel.java:3036)
       at android.os.Parcel.readException(Parcel.java:2978)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6157)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
       at com.bugsnag.android.Client$1.run(Client.java:194)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
