### ISSUE TITLE
Runtime error/crash on Android KitKat (API level 19)

### ISSUE THREAD

**Issue by inetic** [clostra/newnode#70]
```
E/AndroidRuntime(10651): FATAL EXCEPTION: main
E/AndroidRuntime(10651): Process: com.example.webviewsample, PID: 10651
E/AndroidRuntime(10651): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cmsg_nxthdr" referenced by "libdcdn.so"...
E/AndroidRuntime(10651): 	at java.lang.Runtime.loadLibrary(Runtime.java:364)
E/AndroidRuntime(10651): 	at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime(10651): 	at com.clostra.dcdn.Dcdn.<clinit>(Dcdn.java:5)
E/AndroidRuntime(10651): 	at com.example.webviewsample.MainActivity.onCreate(MainActivity.java:48)
E/AndroidRuntime(10651): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime(10651): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(10651): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/AndroidRuntime(10651): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime(10651): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime(10651): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime(10651): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10651): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(10651): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(10651): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10651): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(10651): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(10651): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(10651): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  477):   Force finishing activity com.example.webviewsample/.MainActivity
```

I also saw `rand` missing.

Seems to me that KitKat is still [quite common](https://deviceatlas.com/blog/android-versions-market-share-2016) to be ignored, especially in Asia and Middle East.

**Comment by inetic** [comment]
Relevant link:

https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md

**Comment by shalunov** [comment]
Looks like we would need to build to API level 19 to deal.

**Comment by inetic** [comment]
I just tried with an android with Marshmallow (API level 23) on it and it's failing with a similar message

```
07-13 11:07:10.144 26493 26493 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memset8" referenced by "/data/app/com.example.webviewsample-1/lib/arm/libdcdn.so"...
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at com.clostra.dcdn.Dcdn.<clinit>(Dcdn.java:5)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at com.clostra.dcdn.Dcdn.init(Dcdn.java:12)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at com.example.webviewsample.MainActivity.onCreate(MainActivity.java:48)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6303)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:153)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5441)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
07-13 11:07:10.144 26493 26493 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

Implying that if the code does work on Androids, it does so only on the most modern ones (currently Nougat with API level 24 and 25) with the current market share of [~11.5%](https://developer.android.com/about/dashboards/index.html) **globally**, and very likely a lot less in the countries of interest.

**Comment by inetic** [comment]
> Looks like we would need to build to API level 19 to deal.

Yes, that is what my googling got me to believe as well. I _think_ building dCDN with that API level shouldn't be a problem, it's the web view example app which seems to make use of the high API level.

**Comment by inetic** [comment]
Got it working with Marshmallow (NDK API 23) by changing [this](https://github.com/inetic/dcdn/commit/c3ce1ad4426d7c12e760aa00b89953dd38225c3b). I was however not successful with lowering that further (some compilation error I haven't looked much into yet).

Trying to run the android-23 version on an android-19 device now gives me the [missing `rand` symbol error](https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#Cannot-Locate-Symbol).
